# Generated by Django 3.2 on 2024-12-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20241215_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название объекта применения')),
                ('slug', models.SlugField(verbose_name='product_slug')),
            ],
            options={
                'verbose_name': 'Тег для товара',
                'verbose_name_plural': 'Теги для товара',
            },
        ),
        migrations.CreateModel(
            name='TagForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название отрасли')),
                ('slug', models.SlugField(verbose_name='project_slug')),
            ],
            options={
                'verbose_name': 'Тег для проекта',
                'verbose_name_plural': 'Теги для проекта',
            },
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выхода новости'),
        ),
        migrations.AlterField(
            model_name='region',
            name='coords',
            field=models.CharField(max_length=256, verbose_name='Координаты регионального центра.'),
        ),
        migrations.CreateModel(
            name='TagProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
                ('project_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tagforproject')),
            ],
            options={
                'verbose_name': 'Тег товара',
                'verbose_name_plural': 'Теги товара',
            },
        ),
        migrations.CreateModel(
            name='TagProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.product')),
                ('product_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tagforproduct')),
            ],
            options={
                'verbose_name': 'Тег товара',
                'verbose_name_plural': 'Теги товара',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(through='content.TagProduct', to='content.TagForProduct', verbose_name='Теги товара'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tags',
            field=models.ManyToManyField(through='content.TagProject', to='content.TagForProject', verbose_name='Теги проекта'),
        ),
        migrations.AddConstraint(
            model_name='tagproject',
            constraint=models.UniqueConstraint(fields=('project_tag', 'project'), name='unique_tagproject'),
        ),
        migrations.AddConstraint(
            model_name='tagproduct',
            constraint=models.UniqueConstraint(fields=('product_tag', 'product'), name='unique_tagproduct'),
        ),
    ]
