# Generated by Django 3.2 on 2024-11-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода новости')),
                ('text', models.TextField()),
                ('image', models.ImageField(default=None, null=True, upload_to='content/news_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_description', models.TextField(max_length=256)),
                ('preview', models.ImageField(default=None, null=True, upload_to='content/products_images')),
            ],
        ),
    ]
