# Generated by Django 3.2 on 2025-06-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField(verbose_name='Текст с описанием компании в самом верху страницы')),
                ('colleagues_description', models.TextField(null=True, verbose_name="Текст для раздела 'Команда'")),
                ('colleagues_main_image', models.ImageField(blank=True, null=True, upload_to='company_image/', verbose_name="Общее фото для раздела 'Команда'")),
            ],
            options={
                'verbose_name': "Наполнение раздела 'О нас'",
                'verbose_name_plural': "Наполнение раздела 'О нас' (должно быть одно)",
            },
        ),
        migrations.CreateModel(
            name='AboutIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почтой')),
                ('address', models.TextField(default=None, verbose_name='Адрес предприятия')),
                ('slogan', models.TextField(verbose_name='Слоган')),
                ('description_1', models.TextField(verbose_name="Описание 'О компании' для первого блока главной страницы")),
                ('description_2', models.TextField(verbose_name="Описание 'О компании' для второго блока главной страницы")),
            ],
            options={
                'verbose_name': 'Наполнение главной страницы',
                'verbose_name_plural': 'Наполнение главной страницы (должно быть одно)',
            },
        ),
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('position', models.TextField(verbose_name='Должность')),
                ('image', models.ImageField(upload_to='colleagues_images/', verbose_name='Фотография сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник компании',
                'verbose_name_plural': 'Сотрудники компании',
            },
        ),
        migrations.CreateModel(
            name='IndustryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название отрасли')),
                ('slug', models.SlugField(verbose_name='Slug отрасли (должен быть на английском языке)')),
            ],
            options={
                'verbose_name': 'Отрасль для продуктов и проектов',
                'verbose_name_plural': 'Отрасли для продуктов и проектов',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Заголовок новости')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата выхода новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('video', models.FileField(blank=True, null=True, upload_to='news_videos/', verbose_name='Видео новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название объекта применения')),
                ('slug', models.SlugField(verbose_name='Slug объекта применения (должен быть на английском языке)')),
            ],
            options={
                'verbose_name': 'Объект применения для продуктов и проектов',
                'verbose_name_plural': 'Объекты применения для продуктов и проектов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название продукта')),
                ('short_description', models.TextField(max_length=256, verbose_name='Краткое описание продукта')),
                ('description', models.TextField(verbose_name='Полное описание продукта')),
                ('preview', models.ImageField(default=None, null=True, upload_to='products_images', verbose_name='Фотография продукта')),
                ('specifications', models.TextField(default=None, verbose_name='Основные технические характеристики')),
                ('applying_objects', models.ManyToManyField(blank=True, related_name='products', to='content.ObjectTag', verbose_name='Объекты применения')),
                ('industries', models.ManyToManyField(blank=True, related_name='products', to='content.IndustryTag', verbose_name='Отрасли')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects_images', verbose_name='Фотография проекта')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Город/точное местоположение')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название региона')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображается на карте')),
                ('coord_x', models.FloatField(default=1.0, verbose_name='Координата X (долгота)')),
                ('coord_y', models.FloatField(default=1.0, verbose_name='Координата Y (широта)')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
            ],
            options={
                'verbose_name': 'Продукт в проекте',
                'verbose_name_plural': 'Продукты в проекте',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='regions',
            field=models.ManyToManyField(related_name='projects', to='content.Region', verbose_name='Регионы проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_products',
            field=models.ManyToManyField(blank=True, through='content.ProjectProduct', to='content.Product', verbose_name='Используемые продукты'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag_object',
            field=models.ManyToManyField(related_name='projects', to='content.ObjectTag', verbose_name='Объект применения'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag_sphere',
            field=models.ManyToManyField(related_name='projects', to='content.IndustryTag', verbose_name='Отрасль'),
        ),
        migrations.CreateModel(
            name='ProductPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/products/', verbose_name='Файл')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='content.product', verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'PDF-файл продукта',
                'verbose_name_plural': 'PDF-файлы продуктов',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Фотография новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.new', verbose_name='Новость, которой назначается фотография')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новостей',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основная карта', max_length=100, verbose_name='Название карты')),
                ('regions', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='maps', to='content.Region', verbose_name='Регионы на карте')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карта (должна быть одна)',
            },
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo_images/', verbose_name='Логотип компании-заказчика')),
                ('about_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_images', to='content.aboutcompany', verbose_name="Модель раздела 'О нас'")),
            ],
            options={
                'verbose_name': 'Логотип компании-заказчика',
                'verbose_name_plural': 'Логотипы компаний-заказчиков',
            },
        ),
        migrations.CreateModel(
            name='CompanyPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/company/', verbose_name='PDF-файл')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('about_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='content.aboutcompany', verbose_name="Модель наполнения раздела 'О нас'")),
            ],
            options={
                'verbose_name': 'PDF-файл компании',
                'verbose_name_plural': 'PDF-файлы компании',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='content.aboutindex')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='colleagues',
            field=models.ManyToManyField(blank=True, related_name='companies', to='content.Colleague', verbose_name='Коллеги'),
        ),
    ]
