# Generated by Django 3.2 on 2025-03-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почтой')),
                ('address', models.TextField(default=None, verbose_name='Адрес предприятия')),
                ('slogan', models.TextField(verbose_name='Слоган')),
                ('description_1', models.TextField(verbose_name="Описание 'О нас' для первого блока")),
                ('description_2', models.TextField(verbose_name="Описание 'О нас' для второго блока")),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField(verbose_name='Текст с описанием компании в самом верху страницы')),
                ('pdfs', models.FileField(upload_to='pdfs/company/', verbose_name="PDF-файл для страницы 'О компании'")),
                ('logo_images', models.ImageField(default=None, null=True, upload_to='logo_images/', verbose_name='Логотип заказчика')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Карта',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Заголовок новости')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата выхода новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('image', models.ImageField(default=None, null=True, upload_to='news_images/', verbose_name='Фотография новости')),
                ('video', models.FileField(blank=True, null=True, upload_to='news_videos/', verbose_name='Видео новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название продукта')),
                ('short_description', models.TextField(max_length=256, verbose_name='Краткое описание продукта')),
                ('description', models.TextField(verbose_name='Полное описание продукта')),
                ('preview', models.ImageField(default=None, null=True, upload_to='products_images', verbose_name='Фотография продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(default=None, null=True, upload_to='projects_images', verbose_name='Фотография проекта')),
                ('location', models.TextField(default=None, null=True, verbose_name='Город, более точное местоположение проекта.')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название региона')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображается на карте')),
                ('coords', models.CharField(max_length=256, verbose_name='Координаты регионального центра.')),
            ],
            options={
                'verbose_name': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='TagForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название отрасли')),
                ('slug', models.SlugField(verbose_name='project_slug')),
            ],
            options={
                'verbose_name': 'Тег для проекта',
                'verbose_name_plural': 'Теги для проекта',
            },
        ),
        migrations.CreateModel(
            name='TechnicalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Основная характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_descriptions', to='content.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.region')),
            ],
            options={
                'verbose_name': 'Регионы проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
            ],
            options={
                'verbose_name': 'Продукты в проекте',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ManyToManyField(through='content.ProjectRegion', to='content.Region', verbose_name='Местоположение проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_products',
            field=models.ManyToManyField(through='content.ProjectProduct', to='content.Product', verbose_name='Продукты, используемые в проекте'),
        ),
        migrations.CreateModel(
            name='MapRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.map')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.region')),
            ],
            options={
                'verbose_name': 'Регионы на карте',
            },
        ),
        migrations.AddField(
            model_name='map',
            name='regions',
            field=models.ManyToManyField(through='content.MapRegion', to='content.Region', verbose_name='Регионы на карте'),
        ),
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя коллеги')),
                ('position', models.TextField(verbose_name='Должность')),
                ('image', models.ImageField(upload_to='colleagues_images/', verbose_name='Фотография коллеги')),
                ('about_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleagues_list', to='content.aboutcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='content.about')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='colleagues',
            field=models.ManyToManyField(blank=True, related_name='companies', to='content.Colleague', verbose_name='Коллеги'),
        ),
    ]
