# Generated by Django 3.2.3 on 2025-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='colleagues_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_image/', verbose_name="Общее фото для раздела 'Команда'"),
        ),
    ]
