# Generated by Django 3.2 on 2025-03-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='colleagues',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='content.Colleague', verbose_name='Коллеги'),
        ),
    ]
