# Generated by Django 3.2 on 2024-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/news_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(default=None, null=True, upload_to='media/products_images'),
        ),
    ]
