# Generated by Django 3.2 on 2025-03-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20250302_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='colleagues_description',
            field=models.TextField(null=True, verbose_name="Текст для раздела 'Команда'"),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='colleagues_main_image',
            field=models.ImageField(default=123, upload_to='', verbose_name="Общее фото для раздела 'Команда'"),
            preserve_default=False,
        ),
    ]
