# Generated by Django 3.2 on 2025-03-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20250302_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='logo_images',
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='colleagues_main_image',
            field=models.ImageField(upload_to='company_image/', verbose_name="Общее фото для раздела 'Команда'"),
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo_images/', verbose_name='Логотип компании')),
                ('about_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_images', to='content.aboutcompany')),
            ],
        ),
    ]
