# Generated by Django 3.2 on 2025-03-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20250302_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='pdfs',
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/company/')),
                ('about_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='content.aboutcompany')),
            ],
        ),
    ]
