# Generated by Django 3.2 on 2025-03-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20250302_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/company/')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('about_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='content.aboutcompany')),
            ],
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
