# Generated by Django 3.2 on 2025-01-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='logo',
        ),
        migrations.AddField(
            model_name='about',
            name='description_1',
            field=models.TextField(default=1234, verbose_name="Описание 'О нас' для первого блока"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_2',
            field=models.TextField(default=1234, verbose_name="Описание 'О нас' для второго блока"),
            preserve_default=False,
        ),
    ]
