# Generated by Django 3.2 on 2025-03-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20250302_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutIndex',
        ),
    ]
