# Generated by Django 3.2 on 2025-01-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20250119_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.TextField(default=1234, verbose_name='Слоган'),
            preserve_default=False,
        ),
    ]
