# Generated by Django 3.2 on 2025-03-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_about_aboutindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutindex',
            options={'verbose_name': 'Модель для главной страницы', 'verbose_name_plural': 'Модели для главной страницы'},
        ),
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Фотография новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.new')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новостей',
            },
        ),
    ]
