# Generated by Django 3.2.3 on 2025-03-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20250302_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/products/')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='content.product')),
            ],
            options={
                'verbose_name': 'PDF файл продукта',
                'verbose_name_plural': 'PDF файлы продуктов',
            },
        ),
    ]
