# Generated by Django 3.2 on 2025-02-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_about_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/', verbose_name='Видео новости'),
        ),
    ]
