# Generated by Django 3.2 on 2025-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_new_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_description',
            field=models.TextField(default='some techs', verbose_name='Основные характеристики продукта'),
        ),
    ]
