# Generated by Django 3.2.3 on 2025-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_productpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applying_object',
            field=models.TextField(default=None, verbose_name='Объект применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(default=None, verbose_name='Основные технические характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='sphere',
            field=models.TextField(default=None, verbose_name='Отрасль'),
        ),
    ]
