# Generated by Django 3.2 on 2025-02-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_product_technical_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='technical_description',
        ),
        migrations.CreateModel(
            name='TechnicalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Основная характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_descriptions', to='content.product')),
            ],
        ),
    ]
