# Generated by Django 3.2.3 on 2025-03-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20250320_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='applying_object',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sphere',
        ),
    ]
