# Generated by Django 3.2 on 2025-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20250320_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTagForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название отрасли')),
                ('slug', models.SlugField(verbose_name='Отрасль slug')),
            ],
            options={
                'verbose_name': 'Тег для отрасли',
                'verbose_name_plural': 'Теги для отрасли',
            },
        ),
        migrations.CreateModel(
            name='TypeTagForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название типа проекта')),
                ('slug', models.SlugField(verbose_name='Тип проекта slug')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
            },
        ),
        migrations.DeleteModel(
            name='TagForProject',
        ),
        migrations.AddField(
            model_name='project',
            name='tag_sphere',
            field=models.ManyToManyField(related_name='projects', to='content.IndustryTagForProject', verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag_type',
            field=models.ManyToManyField(related_name='projects', to='content.TypeTagForProject', verbose_name='Тип проекта'),
        ),
    ]
