# Generated by Django 3.2 on 2025-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20250324_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTagForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название объекта применения')),
                ('slug', models.SlugField(verbose_name='Тип объекта применения slug')),
            ],
            options={
                'verbose_name': 'Объект применения',
                'verbose_name_plural': 'Объекты применения',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag_type',
        ),
        migrations.DeleteModel(
            name='TypeTagForProject',
        ),
        migrations.AddField(
            model_name='project',
            name='tag_object',
            field=models.ManyToManyField(related_name='projects', to='content.ObjectTagForProject', verbose_name='Объект применения'),
        ),
    ]
